# This is the config file for landscape.io
# https://landscape.io/pages/docs
# https://landscape.io/github/astrofrog/wcsaxes/

ignore-paths:
    - docs/conf.py
    - wcsaxes/version.py
    - wcsaxes/conftest.py
    - wcsaxes/_astropy_init.py
    - wcsaxes/cython_version.py
    - ah_bootstrap.py
    - ez_setup.py
