version: 2

build:
  image: latest

# Install special pinning for RTD first, if any.
# Then install regular dependencies.
python:
  version: 3.6
  install:
    - requirements: docs/rtd_requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

submodules:
  include: all

# Don't build any extra formats
formats: []
