language: python

python:
    - 2.7
    - 2.6
    - 3.3
    - 3.2
env:
    - NUMPY_VERSION=1.7.0 SETUP_CMD='test' OPTIONAL_DEPS=false

matrix:
    include:
        #try alternate numpy versions on both 2.7 and 3.2 - using 3.2 because the numpy builds fail on 3.3
        - python: 2.7
          env: NUMPY_VERSION=1.6.2 SETUP_CMD='test' OPTIONAL_DEPS=false
        - python: 2.7
          env: NUMPY_VERSION=1.5.1 SETUP_CMD='test' OPTIONAL_DEPS=false
        - python: 3.2
          env: NUMPY_VERSION=1.6.2 SETUP_CMD='test' OPTIONAL_DEPS=false
        - python: 3.2
          env: NUMPY_VERSION=1.5.1 SETUP_CMD='test' OPTIONAL_DEPS=false
        # Make sure all the tests also pass with the optional dependences on both 2.x and 3.x
        - python: 2.7
          env: NUMPY_VERSION=1.7.0 SETUP_CMD='test' OPTIONAL_DEPS=true
        - python: 3.3
          env: NUMPY_VERSION=1.7.0 SETUP_CMD='test' OPTIONAL_DEPS=true
        # Make sure egg_info command works on both 2.x and 3.x
        - python: 2.7
          env: NUMPY_VERSION=1.7.0 SETUP_CMD='egg_info' OPTIONAL_DEPS=false
        - python: 3.3
          env: NUMPY_VERSION=1.7.0 SETUP_CMD='egg_info' OPTIONAL_DEPS=false
        # Check for sphinx doc build warnings
        - python: 2.7
          env: NUMPY_VERSION=1.7.0 SETUP_CMD='build_sphinx -w -n' OPTIONAL_DEPS=false

before_install:
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq
   - if [[ $SETUP_CMD != egg_info ]]; then sudo apt-get install -qq python-numpy cython libatlas-dev liblapack-dev gfortran; fi
   - if $OPTIONAL_DEPS; then sudo apt-get install -qq python-scipy libhdf5-serial-1.8.4 libhdf5-serial-dev; fi
   - if [[ $SETUP_CMD == build_sphinx* ]]; then sudo apt-get install -qq python-sphinx graphviz texlive-latex-extra dvipng; fi

install:
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip install --upgrade "numpy==$NUMPY_VERSION" -q --use-mirrors
   - if $OPTIONAL_DEPS; then pip install scipy --use-mirrors; fi # this can't be quiet because it takes so long that travis times out
   - if $OPTIONAL_DEPS; then pip install h5py -q --use-mirrors; fi
   - if [[ $SETUP_CMD == build_sphinx* ]]; then pip -q install sphinx --use-mirrors; fi
   - if [[ $SETUP_CMD != egg_info ]]; then pip -q install Cython --use-mirrors; fi

script:
   - export OPEN_FILES=""
   - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]] || [[ $TRAVIS_PYTHON_VERSION == "3.2" ]] && [[ $NUMPY_VERSION == "1.6.2" ]] && [[ $SETUP_CMD == "test" ]]; then export OPEN_FILES=--open-files; fi
   - python setup.py $SETUP_CMD $OPEN_FILES
