language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

python:
    - 2.7
    - 3.4
    - 3.5

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MATPLOTLIB_VERSION=1.5
        - CONDA_DEPENDENCIES='pyqt nose matplotlib pillow'
        - PIP_DEPENDENCIES='pytest-mpl'
        - SETUP_XVFB=True
    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test --remote-data'

matrix:
    include:

        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage --remote-data'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Try Astropy development and LTS versions
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='test --remote-data'
        - python: 3.5
          env: ASTROPY_VERSION=development SETUP_CMD='test --remote-data'
        - python: 2.7
          env: ASTROPY_VERSION=lts SETUP_CMD='test --remote-data'
        - python: 3.5
          env: ASTROPY_VERSION=lts SETUP_CMD='test --remote-data'

        # Try all python versions with the latest numpy
        - python: 3.3
          env: SETUP_CMD='test --remote-data' NUMPY_VERSION=1.9

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.9 SETUP_CMD='test --remote-data'
        - python: 2.7
          env: NUMPY_VERSION=1.8 SETUP_CMD='test --remote-data'
        - python: 2.7
          env: NUMPY_VERSION=1.7 SETUP_CMD='test --remote-data'
        - python: 2.7
          env: NUMPY_VERSION=1.6 SETUP_CMD='test --remote-data'

        # Try older matplotlib versions
        - python: 3.5
          env: MATPLOTLIB_VERSION=1.5 SETUP_CMD='test --remote-data'

before_install:

    # Make sure matplotlib uses PyQT not PySide
    - export QT_API=pyqt

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage --remote-data' ]]; then
          coveralls --rcfile='wcsaxes/tests/coveragerc';
      fi
