language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8

    # Install the pip that supports wheel
    - pip install setuptools --upgrade
    - pip install pip --upgrade
    - pip install wheel

    # We do this to make sure we get dependencies so pip works below
    # Note that travis does *not* use python packages installed via apt - it
    # does all the building in an isolated virtualenv
    - sudo apt-get update

    # CORE DEPENDENCIES
    - if [[ $SETUP_CMD != egg_info ]]; then sudo apt-get install python-numpy; fi

install:
    - pip install --upgrade numpy
    - pip install matplotlib
    - pip install pytest
    - pip install astropy

script:
    - py.test wcsaxes