variables:
  CIBW_BUILD: cp36-* cp37-* cp38-*

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astropy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:
  - template: publish.yml@OpenAstronomy
    parameters:
      # FIXME: we exclude the test_data_out_of_range test since it
      # currently fails, see https://github.com/astropy/astropy/issues/10409
      test_command: pytest -p no:warnings --astropy-header -k "not test_data_out_of_range" --pyargs astropy
      test_extras: test
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
        pypi_connection_name : 'pypi_endpoint'
      targets:
      - sdist
      - wheels_*linux_i686
      - wheels_*linux_x86_64
      - wheels_macos
      - wheels_*win32
      - wheels_*win_amd64
