version: 2

jobs:
  image-tests-mpl212:
    docker:
      - image: astropy/image-tests-py36-mpl212:1.10
    steps:
      - checkout
      - run:
          name: checkout all of the astropy source code (including astropy/_erfa)
          command: git checkout -qf
      - run:
          name: Run tests
          command: python3 setup.py test -P visualization --remote-data=astropy --open-files -a "--mpl --mpl-results-path=$PWD/results -W ignore:np.asscalar"
      - store_artifacts:
          path: results

  image-tests-mpl222:
    docker:
      - image: astropy/image-tests-py36-mpl222:1.10
    steps:
      - checkout
      - run:
          name: checkout all of the astropy source code (including astropy/_erfa)
          command: git checkout -qf
      - run:
          name: Run tests
          command: python3 setup.py test -P visualization --remote-data=astropy --open-files -a "--mpl --mpl-results-path=$PWD/results -W ignore:np.asscalar"
      - store_artifacts:
          path: results

  image-tests-mpl302:
    docker:
      - image: astropy/image-tests-py37-mpl302:1.10
    steps:
      - checkout
      - run:
          name: checkout all of the astropy source code (including astropy/_erfa)
          command: git checkout -qf
      - run:
          name: Run tests
          command: python3 setup.py test -P visualization --remote-data=astropy --open-files -a "--mpl --mpl-results-path=$PWD/results"
      - store_artifacts:
          path: results

  image-tests-mpl310:
    docker:
      - image: astropy/image-tests-py37-mpl311:1.10
    steps:
      - checkout
      - run:
          name: checkout all of the astropy source code (including astropy/_erfa)
          command: git checkout -qf
      - run:
          name: Run tests
          command: python3 setup.py test -P visualization --remote-data=astropy --open-files -a "--mpl --mpl-results-path=$PWD/results"
      - store_artifacts:
          path: results

  image-tests-mpldev:
    docker:
      - image: astropy/image-tests-py37-base:1.4
    steps:
      - checkout
      - run:
          name: checkout all of the astropy source code (including astropy/_erfa)
          command: git checkout -qf
      - run:
          name: Install C++ compiler
          command: |
            apt update
            apt install -y g++
      - run:
          name: Install Python dependencies, including developer version of Matplotlib
          command: pip3 install pytest pytest-mpl pytest-astropy numpy scipy git+https://github.com/matplotlib/matplotlib.git
      - run:
          name: Run tests
          command: python3 setup.py test -P visualization --remote-data=astropy --open-files -a "--mpl --mpl-results-path=$PWD/results"
      - store_artifacts:
          path: results

workflows:
  version: 2
  tests:
    jobs:
      - image-tests-mpl212
      - image-tests-mpl222
      - image-tests-mpl302
      - image-tests-mpl310
      - image-tests-mpldev
