version: 2

jobs:
  html-docs:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Fetching submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: Install dependencies and build docs
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install sphinx astropy-sphinx-theme
            cd docs
            make html


workflows:
  version: 2
  tests_and_docs:
    jobs:
      - html-docs
